# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['MYSQL_USERNAME'] || "root" %>
  password: <%= ENV['MYSQL_PASSWORD'] || "1234" %>
  host: localhost

development:
  <<: *default
  database: realtime_search_development

test:
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['MYSQL_USERNAME'] || "root" %>
  password: <%= ENV['MYSQL_PASSWORD'] || "1234" %>
  host: <%= ENV['MYSQL_HOST'] || "localhost" %>
  port: <%= ENV['MYSQL_PORT'] || "3306" %>
  database: realtime_search_test

