# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['MYSQL_USERNAME'] %>
  password: <%= ENV['MYSQL_PASSWORD']%>
  host: <%= ENV['MYSQL_HOST']%>
  port: <%= ENV['MYSQL_PORT']%>
  collation: utf8mb4_unicode_ci

development:
  <<: *default
  database: realtime_search_development

test:
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['MYSQL_USERNAME'] %>
  password: <%= ENV['MYSQL_PASSWORD']%>
  host: <%= ENV['MYSQL_HOST']%>
  port: <%= ENV['MYSQL_PORT']%>
  database: realtime_search_test
  collation: utf8mb4_unicode_ci

production:
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['MYSQL_USERNAME'] %>
  password: <%= ENV['MYSQL_PASSWORD']%>
  host: <%= ENV['MYSQL_HOST']%>
  port: <%= ENV['MYSQL_PORT']%>
  database: realtime_search_production
  collation: utf8mb4_unicode_ci